// PergaminoTextos.cpp
//
// Textos de los pergaminos del juego
/////////////////////////////////////////////////////////////////////////////

#include "Pergamino.h"

using namespace Abadia;

/////////////////////////////////////////////////////////////////////////////
// pergamino de la presentación
/////////////////////////////////////////////////////////////////////////////


// TODO poner cada texto en includes que se puedan modificar mejor
//const char * Pergamino::pergaminoInicio[8] = 
const unsigned char * Pergamino::pergaminoInicio[8] =
		{ // 0 Castellano
	(const unsigned char*)
	" Ya al final de mi\x0d"
	"vida de pecador, mien-\x0d"
	"tras espero el mo-\x0d"
	"mento de perderme en\x0d"
	"el abismo sin fondo de\x0d"
	"la divinidad desierta y\x0d"
	"silenciosa; en esta\x0d"
	"celda de mi querido\x0d"
	"monasterio de Melk,\x0d"
	"donde aun me retiene\x0d"
	"mi cuerpo pesado y\x0d"
	"enfermo, me dispongo\x0d"
	"a dejar constancia en\x0d"
	"este pergamino de los\x0d"
	"hechos asombrosos y\x0d"
	"terribles que me fue\x0d"
	"dado presenciar en mi\x0d"
	"juventud.\x0d\x0d"
	" El sewor me conce-\x0d"
	"de la gracia de dar\x0d"
	"fiel testimonio de los\x0d"
	"acontecimientos que se\x0d"
	"produjeron en la aba-\x0d"
	"dia cuyo nombre in-\x0d"
	"cluso conviene ahora\x0d"
	"cubrir con un piadoso\x0d"
	"manto de silencio; ha-\x0d"
	"cia finales de 1327,\x0d"
	"cuando mi padre deci-\x0d"
	"dio que acompawara a\x0d"
	"fray Guillermo de \x0d"
	"Occam, sabio francis-\x0d"
	"cano que estaba a\x0d"
	"punto de iniciar una\x0d"
	"mision en el desem-\x0d"
	"pewo de la cual to-\x0d"
	"caria muchas ciuda-\x0d"
	"des famosas y aba-\x0d"
	"dias antiquisimas. Asi\x0d"
	"fue como me conver-\x0d"
	"ti al mismo tiempo en\x0d"
	"su amanuense y dis-\x0d"
	"cipulo; y no tuve que\x0d"
	"arrepentirme, porque\x0d"
	"con el fui testigo de\x0d"
	"acontecimientos dignos\x0d"
	"de ser registrados,\x0d"
	"para memoria de los\x0d"
	"que vengan despues.\x0d\x0d"
	" Asi, mientras con\x0d"
	"los dias iba conocien-\x0d"
	"do mejor a mi maes-\x0d"
	"tro, llegamos a las\x0d"
	"faldas del monte don-\x0d"
	"de se levantaba la\x0d"
	"abadia. Y ya es hora\x0d"
	"de que, como nosotros\x0d"
	"entonces, a ella se\x0d"
	"acerque mi relato, y\x0d"
	"ojala mi mano no\x0d"
	"tiemble cuando me\x0d"
	"dispongo a narrar lo\x0d"
	"que sucedio despues...\x0d"
	"\x0d"
	"\x0d"
	"\x0d"
	"\x0d"
	"\x0d"
	"autor: \x0d"
	"    Paco Menendez\x0d\x0d"
	"graficos y caratula: \x0d"
	"    Juan Delcan\x0d\x0d"
	"reingenieria inversa: \x0d"
	"    Manuel Abadia\x0d\x0d"
	"version SDL: Luzbel\x1a",
// TODO añadir creditos graficos VGA a Antonio Giner
		// fin textos 0 castellano
		// 1 inglés
	(const unsigned char*)
	" Having reached the\x0d"
	"end of my poor sin-\x0d"
	"ner's life, waiting to\x0d"
	"be lost in the bottom-\x0d"
	"less pit of silent and\x0d"
	"deserted divinity;\x0d"
	"confined now with my\x0d"
	"heavy, ailing body in\x0d"
	"this cell in the dear\x0d"
	"monastery of Melk, I\x0d"

	"prepare to leave on\x0d"
	"this parchment my\x0d"
	"testimony as to the\x0d"
	"wondrous and terrible\x0d"
	"events that I happened\x0d"
	"to observe in my\x0d"
	"youth.\x0d\x0d"
	" May the Lord grant\x0d"
	"me the grace to be\x0d"

	"the transparent wit-\x0d"
	"ness of the happenings\x0d"
	"that took place in the\x0d"
	"abbey whose name it\x0d"
	"is only right and pious\x0d"
	"now to omit, toward\x0d"
	"the year of our Lord\x0d"
	"1327, when my father\x0d"
	"decided to place me\x0d"
	"under the direction of\x0d"

	"a learned Franciscan,\x0d"
	"Brother William of\x0d"
	"Baskerville, about to\x0d"
	"undertake a mission\x0d"
	"that would lead him to\x0d"
	"famous cities and an-\x0d"
	"cient abbeys. Thus I\x0d"
	"became William's\x0d"
	"scribe and discipline\x0d"
	"at the same time, nor\x0d"

	"did I ever regret it,\x0d"
	"because with him I\x0d"
	"was witness to events\x0d"
	"worthy of being handed\x0d"
	"down, to those who\x0d"
	"will come after us.\x0d\x0d"
	" And so, after I had\x0d"
	"come to know my\x0d"
	"master day by day,\x0d"
	"we reached the foot\x0d"
	"of the hill on which\x0d"
	"the abbey stood. And\x0d"
	"it is time for my\x0d"
	"story to approach it,\x0d"
	"as we did then, and\x0d"
	"may my hand remain\x0d"
	"steady as I prepare\x0d"
	"to tell what happened...\x0d\x0a"

	"Author:Paco Menendez\x0d"
	"Graphics and cover:\x0d"
	"     Juan Delcan\x0d"
	"Copyright: Opera Soft\x0d"
	"reverse engineering:\x0d"
	"    Manuel Abadia\x0d"
	"version SDL: Luzbel\x0d"
	"VGA Graphs and\x0d"
	"english translation:\x0d"
	"     Antonio Giner\x1a",

		// fin textos 1 inglés
		// textos 2 portugues brasil

	(const unsigned char*)
	" Chegando ao fim\x0d"
	"desta minha vida de\x0d"
	"pecador, enquanto, en-\x0d"
	"canecido, envelheço\x0d"
	"como o mundo, à es-\x0d"
	"pera de perder-me no\x0d"
	"abismo sem fundo da\x0d"
	"divindade silenciosa e\x0d"
	"deserta, doente e com\x0d"
	"o corpo entrevado\x0d"
	"nesta cela do caro\x0d"
	"mosteiro de Melk,\x0d"
	"apresto-me a deixar\x0d"
	"neste pergaminho o\x0d"
	"testemunho de terrí-\x0d"
	"veis e increíveis\x0d"
	"eventos que na ju-\x0d"
	"ventude me foi dado\x0d"
	"assistir.\x0d\x0d"
	" Concedei a mim,\x0d"
	"Senhor, a graça de\x0d"
	"ser testemunha trans-\x0d"
	"parente dos aconteci-\x0d"
	"mentos que tiveram\x0d"
	"lugar na abadia, da\x0d"
	"qual, afinal, e piedoso\x0d"
	"que se cale também o\x0d"
	"nome, ao findar do ano\x0d"
	"do Senhor de 1327,\x0d"
	"quando eu, como noviço\x0d"
	"beneditino do mosteiro\x0d"
	"de Melk, fui tirado da\x0d"
	"tranqüilidade do claus-\x0d"
	"tro por meu pai e\x0d"
	"por ele colocado sob a\x0d"
	"tutela de Frei Gui-\x0d"
	"lherme de Baskerville,\x0d"
	"amigo seu e sábio\x0d"
	"franciscano, que esta-\x0d"
	"va para iniciar uma\x0d"
	"missão que o levaria\x0d"
	"a cidades famosas e\x0d"
	"abadias antiqüíssimas.\x0d"
	"Tornei-me assim seu\x0d"
	"escrivão e discípulo\x0d"
	"ao mesmo tempo, e\x0d"
	"nem tive do que me\x0d"
	"arrepender, porque fui\x0d"
	"testemunha com meu\x0d"
	"mestre de aconteci-\x0d"
	"mentos dignos de se-\x0d"
	"rem consignados, como\x0d"
	"agora estou fazendo,\x0d"
	"para memória daqueles\x0d"
	"que virão.\x0d\x0d"
	" Assim, conhecendo\x0d"
	"melhor dia a dia meu\x0d"
	"mestre, passando as\x0d"
	"longas horas de mar-\x0d"
	"cha em longas conver-\x0d"
	"sas atingimos as fal-\x0d"
	"das do monte sobre o\x0d"
	"qual se erguia a aba-\x0d"
	"dia. E, é hora que,\x0d"
	"como fizemos então,\x0d"
	"dela se aproxime mi-\x0d"
	"nha narrativa, e possa\x0d"
	"minha mão não tremer\x0d"
	"quando começar a con-\x0d"
	"tar o que aconteceu\x0d"
	"em seguida...\x0d\x0a"

	"autor: Paco Menendez\x0d"
	"gráficos e imagens:\x0d"
	"    Juan Delcan\x0d"
	"direitos autorais:\x0d"
	"    Opera Soft\x0d"
	"adaptação: Luzbel,\x0d"
	"    Manuel Abadia,\x0d"
	"    Antonio Giner\x0d"
	"tradução:\x0d"
	"    Antonio Pimentel\x1a"
		,
		// fin textos 2 portugues brasil
		// textos 3 CATALAN

	(const unsigned char*)
	" Ja al final de la\x0d"
	"meva vida de pecador,\x0d"
	"mentre espero el mo-\x0d"
	"ment de perdre'm a\x0d"
	"l'abisme sense fons\x0d"
	"de la divinitat deser-\x0d"
	"ta i silenciosa; a\x0d"
	"aquesta cel.la del meu\x0d"
	"estimat monestir de\x0d"
	"Melk, on encara em\x0d"
	"reté el meu cos pesat\x0d"
	"i malalt, em disposo\x0d"
	"a deixar constància\x0d"
	"en aquest pergamí\x0d"
	"dels fets sorprenents\x0d"
	"i terribles que vaig\x0d"
	"presenciar en la meva\x0d"
	"juventut.\x0d\x0d"
	"El Senyor em conce-\x0d"
	"deix la gràcia de do-\x0d"
	"nar fidel testimoni\x0d"
	"dels esdeveniments\x0d"
	"que es van produir a\x0d"
	"l'abadia el nom de la\x0d"
	"qual fins i tot ara\x0d"
	"cal embolcallar amb\x0d"
	"un piadós mantell de\x0d"
	"silenci; cap a finals\x0d"
	"de 1327, quan el meu\x0d"
	"pare va decidir que\x0d"
	"acompanyés a fra\x0d"
	"Guillem de Basker-\x0d"
	"ville, savi franciscà\x0d"
	"que estava a punt\x0d"
	"d'iniciar una missió\x0d"
	"l'acompliment de la\x0d"
	"qual tocaria moltes\x0d"
	"ciutats famoses i aba-\x0d"
	"dies antiquíssimes.\x0d"
	"Així va ser com em\x0d"
	"vaig convertir al ma-\x0d"
	"teix temps en el seu\x0d"
	"amanuense i deixeble;\x0d"
	"i no vaig haver de\x0d"
	"penedir-me, perquè\x0d"
	"amb ell vaig ser tes-\x0d"
	"timoni d'esdeveniments\x0d"
	"dignes de ser regis-\x0d"
	"trats, per la memòria\x0d"
	"dels que vinguin des-\x0d"
	"prés.\x0d\x0d"
	" Així, mentre amb\x0d"
	"els dies anava conei-\x0d"
	"xent millor al meu\x0d"
	"mestre, vam arribar\x0d"
	"al peu de la muntanya\x0d"
	"on s'aixecava l'abadia.\x0d"
	"I ja és moment que,\x0d"
	"com nosaltres llavors,\x0d"
	"a ella s'acosti el meu\x0d"
	"relat, i tan de bo la\x0d"
	"meva mà no tremoli\x0d"
	"quan em disposi a na-\x0d"
	"rrar el que va succe-\x0d"
	"ir després...\x0d\x0a"

	"autor:\x0d"
	"    Paco Menendez\x0d"
	"gràfics i caràtula:\x0d"
	"    Juan Delcan\x0d"
	"copyright:\x0d"
	"    Opera Soft\x0d"
	"adaptació: Luzbel,\x0d"
	"    Manuel Abadia,\x0d"
	"    Antonio Giner\x0d"
	"traducció:Efren Garcia\x1a"
	,
		// fin textos 3 CATALAN
		// textos 4 gallego

	(const unsigned char*)
	"  Chegando ao remate\x0d"
	"da miña vida de peca-\x0d"
	"dor, namentres agardo\x0d"
	"o intre de perderme\x0d"
	"no abismo sen fondo\x0d"
	"da divinidade deserta\x0d"
	"e silenciosa; nesta\x0d"
	"cela do meu querido\x0d"
	"mosteiro de Melk, on-\x0d"
	"de inda me retén o\x0d"
	"meu corpo pesado e\x0d"
	"enfermo, dispóñome a\x0d"
	"deixar testemuño neste\x0d"
	"pergamiño dos abraian-\x0d"
	"tes e terribles feitos\x0d"
	"que me foron dados\x0d"
	"presenciar na miña\x0d"
	"xuventude.\x0d\x0d"
	" O Señor me conceda\x0d"
	"a gracia de dar fel\x0d"
	"testemuño dos feitos\x0d"
	"que aconteceron na\x0d"
	"abadía de cuxo nome\x0d"
	"inda agora convén cu-\x0d"
	"brilo cun piadoso manto\x0d"
	"de silencio; cara finais\x0d"
	"do 1327, cando o meu\x0d"
	"pai decidiu que acom-\x0d"
	"pañara a frai Guiller-\x0d"
	"me de Baskerville,\x0d"
	"sabio franciscano que\x0d"
	"estaba a piques de\x0d"
	"principiar unha misión\x0d"
	"no desempeño da cal\x0d"
	"arribaría en moitas\x0d"
	"cidades sonadas e aba-\x0d"
	"dias antiquísimas. Foi\x0d"
	"así como me convertín\x0d"
	"ao mesmo tempo no\x0d"
	"seu amanuense e dis-\x0d"
	"cípulo; e non tiven que\x0d"
	"arrepentirme, porque\x0d"
	"con el fun testemuña\x0d"
	"de feitos dignos de\x0d"
	"seren rexistrados pra\x0d"
	"memoria dos que ve-\x0d"
	"ñan despois.\x0d\x0d"
	"  Deste xeito, namen-\x0d"
	"tres cos dias ía co-\x0d"
	"ñecendo mellor ó meu\x0d"
	"mestre, chegamos ás\x0d"
	"ladeiras do monte on-\x0d"
	"de se erguía a abadia.\x0d"
	"E xa vai sendo hora\x0d"
	"de que, coma nós en-\x0d"
	"tón, a ela se achegue\x0d"
	"o meu relato, e oxalá\x0d"
	"a miña man non tre-\x0d"
	"ma cando me dispoño\x0d"
	"a narra-lo que despois\x0d"
	"aconteceu...\x0d\x0a"

	"autor:\x0d"
	"    Paco Menéndez\x0d"
	"gráficos e carátula:\x0d"
	"    Juan Delcán\x0d"
	"copyright: Opera Soft\x0d"
	"adaptación: Luzbel,\x0d"
	"    Manuel Abadia,\x0d"
	"    Antonio Giner\x0d"
	"tradución:\x0d"
	"    Marcos Maceda\x1a"

		,
		// fin textos 4 gallego
		// textos 5 italiano

	(const unsigned char*)
	"  Giunto al finire\x0d"
	"della mia vita di pec-\x0d"
	"catore, mentre canuto\x0d"
	"senesco come il mon-\x0d"
	"do, nell'attesa di per-\x0d"
	"dermi nell'abisso sen-\x0d"
	"za fondo della divinità\x0d"
	"silenziosa e deserta,\x0d"
	"partecipando della luce\x0d"
	"inconversevole delle\x0d"
	"intelligenze angeliche,\x0d"
	"trattenuto ormai col\x0d"
	"mio corpo greve e\x0d"
	"malato in questa cella\x0d"
	"del caro monastero di\x0d"
	"Melk, mi accingo a\x0d"
	"lasciare su questo ve-\x0d"
	"llo testimonianza degli\x0d"
	"eventi mirabili e tre-\x0d"
	"mendi a cui in gioven-\x0d"
	"tù mi accadde di as-\x0d"
	"sistere.\x0d\x0d"
	"  Il Signore mi con-\x0d"
	"ceda la grazia di es-\x0d"
	"sere testimone traspa-\x0d"
	"rente degli accadimenti\x0d"
	"che ebbero luogo all'\x0d"
	"abbazia di cui è bene\x0d"
	"e pio si taccia ormai\x0d"
	"anche il nome; al fini-\x0d"
	"re dell'anno del Sig-\x0d"
	"nore 1327, cuando mio\x0d"
	"padre decise di pormi\x0d"
	"accanto a un dotto\x0d"
	"francescano, padre\x0d"
	"Guglielmo di Basker-\x0d"
	"ville, il quale stava\x0d"
	"per iniziare una mis-\x0d"
	"sione che lo avrebbe\x0d"
	"portato a toccare città\x0d"
	"famose e abbazie an-\x0d"
	"tichissime. Divenni\x0d"
	"così suo scrivano e\x0d"
	"discepolo al tempo\x0d"
	"stesso, nè ebbi a pen-\x0d"
	"tirmene, perché fui\x0d"
	"con lui testimone di\x0d"
	"avvenimenti degni di\x0d"
	"essere consegnati, co-\x0d"
	"me ora sto facendo,\x0d"
	"alla memoria di co-\x0d"
	"loro che verranno.\x0d\x0d"
	"  Così conoscendo\x0d"
	"giorno per giorno il\x0d"
	"mio maestro, giungem-\x0d"
	"mo alle falde del mon-\x0d"
	"te su cui si ergeva\x0d"
	"l'abbazia. Ed è ora\x0d"
	"che, come noi allora\x0d"
	"facemmo, a essa si\x0d"
	"approssimi il mio\x0d"
	"racconto, e possa la\x0d"
	"mia mano non tremare\x0d"
	"nell'accingermi a dire\x0d"
	"quanto poi accadde...\x0d\x0a"

	"autore:\x0d"
	"    Paco Menendez\x0d"
	"grafici e copertina:\x0d"
	"    Juan Delcan\x0d"
	"copyright: Opera Soft\x0d"
	"adattamento: Luzbel,\x0d"
	"    Manuel Abadia,\x0d"
	"    Antonio Giner\x0d"
	"traduzione:\x0d"
	"    Chiara Bagnoli\x1a"
	,
		// fin textos 5 italiano
		// textos 6 fines

	(const unsigned char*)
	" Syntisen elämäni lo-\x0d"
	"pulla, kun yhtä valko-\x0d"
	"hapsisena vanhuksena\x0d"
	"kuin maailma itse\x0d"
	"odotan katoamistani\x0d"
	"jumaluuden pohjatto-\x0d"
	"mien syvyyksien hil-\x0d"
	"jaisuuteen ja autiuteen\x0d"
	"tullakseni osaksi enke-\x0d"
	"limaailman selittämä-\x0d"
	"töntä ymmärryksen\x0d"
	"valoa ja kun nykyise-\x0d"
	"ssä tilassani raskas\x0d"
	"ja tautinen ruumiini\x0d"
	"pakottaa minut viettä-\x0d"
	"mään aikani tässä\x0d"
	"rakkaan Melkin luos-\x0d"
	"tarin kammiossa, tah-\x0d"
	"don jättää tälle perga-\x0d"
	"mentille todistuksen\x0d"
	"niistä ihmeellisistä\x0d"
	"ja kauhistavista\x0d"
	"tapahtumista, joita\x0d"
	"nuoruudessani jouduin\x0d"
	"seuraamaan.\x0d\x0d"
	"Herra suokoon minulle\x0d"
	"sen armon, että kyke-\x0d"
	"nisin selvästi todista-\x0d"
	"maan niistä tapahtu-\x0d"
	"mista jotka näin luos-\x0d"
	"tarissa, jonka nimes-\x0d"
	"täkin on oikein ja\x0d"
	"hurskasta vaieta.\x0d\x0d"
	"Nämä tapahtumat si-\x0d"
	"joittuvat Herran vuo-\x0d"
	"den 1327 lopulle, jo-\x0d"
	"lloin minut isäni\x0d"
	"toimesta riistettiin\x0d"
	"Melkin luostarin rau-\x0d"
	"hasta ja lähetettiin\x0d"
	"erään oppineen fran-\x0d"
	"siskaanimunkin - fra\x0d"
	"William Baskervillen\x0d"
	"- käytettäväksi, joka\x0d"
	"hänelle uskotun tehtä-\x0d"
	"vän tähden oli lähdö-\x0d"
	"ssä matkalle kuuluihin\x0d"
	"kaupunkeihin ja ikivan-\x0d"
	"hoihin luostareihin.\x0d\x0d"
	" Sillä tavalla minusta\x0d"
	"tuli samanaikaisesti\x0d"
	"sekä hänen kirjurinsa\x0d"
	"että opetuslapsensa,\x0d"
	"eikä minun tarvinnut\x0d"
	"sitä katua, sillä hänen\x0d"
	"kanssaan sain kokea\x0d"
	"tapahtumia, jotka kan-\x0d"
	"nattaa kirjoittaa muis-\x0d"
	"tiin jälkipolville niin\x0d"
	"kuin nyt teen.\x0d\x0d"
	" Sillä tavalla, oppien\x0d"
	"päivä päivältä tunte-\x0d"
	"maan mestariani ja\x0d"
	"käyden matkan pitkinä\x0d"
	"tunteina loputtomia\x0d"
	"keskusteluja, saavuin\x0d"
	"hänen kanssaan sen\x0d"
	"vuoren juurelle, jonka\x0d"
	"huipulla luostari si-\x0d"
	"jaitsi. Ja nyt on aika\x0d"
	"tehdä niin kuin silloin\x0d"
	"teimme ja lähestyä\x0d"
	"sitä tässä tarinassani,\x0d"
	"ja suokoon Herra,\x0d"
	"ettei käteni vapisisi\x0d"
	"alkaessani nyt kertoa\x0d"
	"mitä sitten tapahtui.\x0d\x0a"

	"ohjelmointi:\x0d"
	"    Paco Menendez\x0d"
	"grafiikka:\x0d"
	"    Juan Delcan\x0d"
	"copyright: Opera Soft\x0d"
	"vga grafiikat: Luzbel,\x0d"
	"    Manuel Abadia,\x0d"
	"    Antonio Giner\x0d"
	"suomennos:\x0d"
	"    Riikka Halonen\x1a"
		,
		// fin textos 6 fines
		// textos 7 portugues

	(const unsigned char*)
	" Chegando ao fim da\x0d"
	"minha vida de pecador,\x0d"
	"à espera de me per-\x0d"
	"der no abismo sem\x0d"
	"fundo da divindade\x0d"
	"silenciosa e deserta;\x0d"
	"retido agora pelo meu\x0d"
	"corpo pesado e doente\x0d"
	"nesta cela do querido\x0d"
	"mosteiro de Melk,\x0d"
	"disponho-me a deixar\x0d"
	"neste velo testemunho\x0d"
	"dos admiráveis e te-\x0d"
	"rríveis eventos a que\x0d"
	"na juventude me foi\x0d"
	"dado assistir.\x0d\x0d"
	" O Senhor me conce-\x0d"
	"da a graça de ser\x0d"
	"testmunha transparente\x0d"
	"dos acontecimentos que\x0d"
	"tiveram lugar na aba-\x0d"
	"dia de que é bom e\x0d"
	"piedoso calar agora o\x0d"
	"próprio nome; ao fin-\x0d"
	"dar o ano do Senhor\x0d"
	"de 1327, quando meu\x0d"
	"pai decidiu que eu\x0d"
	"acompanharia um douto\x0d"
	"franciscano, frei Gui-\x0d"
	"lherme de Baskerville,\x0d"
	"que ia iniciar uma\x0d"
	"missão que o levaria\x0d"
	"a visitar cidades fa-\x0d"
	"mosas e abadias anti-\x0d"
	"quíssimas. Assim me\x0d"
	"tornei seu escrivão e\x0d"
	"discípulo ao mesmo\x0d"
	"tempo, e não vim a\x0d"
	"arrepender-me, porque\x0d"
	"fui com ele testemun-\x0d"
	"ha de acontecimentos\x0d"
	"dignos de serem con-\x0d"
	"fiados, como agora\x0d"
	"faço, à memória da-\x0d"
	"queles que hão-de vir.\x0d"
	" Assim conhecendo dia\x0d"
	"a dia melhor o meu\x0d"
	"mestre, chegamos às\x0d"
	"faldas do monte sobre\x0d"
	"o qual se erguia a\x0d"
	"abadia. E é tempo,\x0d"
	"como, como nós então\x0d"
	"fizemos, que dela se\x0d"
	"aproxime o meu rela-\x0d"
	"to, e oxalá que a mi-\x0d"
	"nha mão não trema ao\x0d"
	"preparar-me para di-\x0d"
	"zer quanto depois\x0d"
	"aconteceu....\x0d"

	"autor:\x0d"
	"    Paco Menendez\x0d"
	"gráficos e capa:\x0d"
	"    Juan Delcan\x0d"
	"copyright: Opera Soft\x0d"
	"adaptação: Luzbel,\x0d"
	"    Manuel Abadia,\x0d"
	"    Antonio Giner\x0d"
	"tradução:\x0d"
	"    Filipe Silva\x1a"

		// fin textos 7 portugues
	};

/////////////////////////////////////////////////////////////////////////////
// pergamino del final del juego
/////////////////////////////////////////////////////////////////////////////

//const char * Pergamino::pergaminoFinal[8] = 
const unsigned char * Pergamino::pergaminoFinal[8] = 
	{
		// texto 0 castellano
	(const unsigned char*)
	" Desfigurado por la\x0d"
	"angustia, por el aco-\x0d"
	"so del veneno que ya\x0d"
	"serpenteaba abundante\x0d"
	"por sus venas, el\x0d"
	"otrora venerable ros-\x0d"
	"tro del anciando se\x0d"
	"veia repulsivo y gro-\x0d"
	"tesco.\x0d"
	" Habriamos podido\x0d"
	"atraparlo con calma,\x0d"
	"pero nos precipitamos\x0d"
	"con vehemencia sobre\x0d"
	"el. Logro zafarse y\x0d"
	"apreto el libro contra\x0d"
	"su pecho para defen-\x0d"
	"derlo. Yo lo tenia co-\x0d"
	"gido con la mano iz-\x0d"
	"quierda, mientras con\x0d"
	"la derecha trataba de\x0d"
	"mantener en alto la\x0d"
	"lampara. Pero roce\x0d"
	"su rostro con la lla-\x0d"
	"ma y emitio un so-\x0d"
	"nido ahogado, casi un\x0d"
	"rugido, dejando caer\x0d"
	"trozos de folio por\x0d"
	"la boca. Su mano\x0d"
	"derecha solto el li-\x0d"
	"bro, busco la lampa-\x0d"
	"ra y, de un golpe, me\x0d"
	"la arranco lanzandola\x0d"
	"hacia adelante...\x0d"
	" Se derramo el acei-\x0d"
	"te y en seguida el\x0d"
	"fuego prendio en el\x0d"
	"pergamino que ardio\x0d"
	"como un haz de hor-\x0d"
	"nija reseca. Todo su-\x0d"
	"cedio en pocos instan-\x0d"
	"tes; una llamarada se\x0d"
	"elevo desde los libros,\x0d"
	"como si aquellas pa-\x0d"
	"ginas milenarias lle-\x0d"
	"varan siglos esperan-\x0d"
	"do quemarse y goza-\x0d"
	"ran al satisfacer de\x0d"
	"pronto una sed inme-\x0d"
	"morial de ecpirosis.\x0d"
	" La abadia ardio du-\x0d"
	"rante tres dias y tres\x0d"
	"noches y de nada va-\x0d"
	"lieron los ultimos es-\x0d"
	"fuerzos.  Al tercer\x0d"
	"dia, curados los heri-\x0d"
	"dos, enterrados los\x0d"
	"cadaveres que habian\x0d"
	"quedado fuera de los\x0d"
	"edificios, los monjes\x0d"
	"y el resto de los po-\x0d"
	"bladores de la abadia\x0d"
	"recogieron sus perte-\x0d"
	"nencias y abandonaron\x0d"
	"la meseta, que aun\x0d"
	"humeaba, como un lu-\x0d"
	"gar maldito.\x0d"
	" Guillermo y yo nos\x0d"
	"alejamos de aquel pa-\x0d"
	"raje en dos cabalga-\x0d"
	"duras que encontramos\x0d"
	"por el bosque. Cuando\x0d"
	"llegamos a  Munich\x0d"
	"tuve que separarme,\x0d"
	"no sin derramar\x0d"
	"abundantes lagrimas,\x0d"
	"de mi buen maestro.\x0d"
	"Despues de darme\x0d"
	"muchos buenos con-\x0d"
	"sejos para mis fu-\x0d"
	"turos estudios, me\x0d"
	"estrecho entre sus\x0d"
	"brazos, con la ter-\x0d"
	"nura de un padre, y\x0d"
	"me dijo adios. Jamas\x0d"
	"volvi a verlo.\x0d"
	" Ahora, ya en el um-\x0d"
	"bral de la muerte,\x0d"
	"cuanto mas releo la\x0d"
	"historia que de ello ha\x0d"
	"resultado, menos se\x0d"
	"si esta contiene o no\x0d"
	"una trama distinguible\x0d"
	"de la mera sucesion\x0d"
	"natural de los aconte-\x0d"
	"cimientos y de los\x0d"
	"momentos que los re-\x0d"
	"lacionan entre si. Y\x0d"
	"es duro para este\x0d"
	"viejo monje no saber\x0d"
	"si la letra que ha es-\x0d"
	"crito contiene o no\x0d"
	"algun sentido oculto,\x0d"
	"ni si contiene mas de\x0d"
	"uno, o muchos, o nin-\x0d"
	"guno. Pero quizas esta\x0d"
	"incapacidad sea pro-\x0d"
	"ducto de la sombra\x0d"
	"que la gran tiniebla\x0d"
	"que se aproxima, pro-\x0d"
	"yecta sobre este\x0d"
	"mundo ya viejo.\x0d"
	" Hace frio en el\x0d"
	"scriptorium, me duele\x0d"
	"el pulgar. Dejo este\x0d"
	"texto, no se para\x0d"
	"quien, este texto, que\x0d"
	"ya no se de que ha-\x0d"
	"bla.\x0d\x1a"
		// fin textos 0 castellano
	,
		// textos 1 inglés
	

	(const unsigned char*)
	"Disfigured by anxiety,\x0d"
	"by the menace of the\x0d"
	"poison now flowing\x0d"
	"abundantly through his\x0d"
	"veins, the venerable\x0d"
	"figure of the old man\x0d"
	"now seemed disgusting\x0d"
	"and grotesque. We\x0d"
	"could have taken him\x0d"
	"calmly, but we fell on\x0d"
	"him with violence; he\x0d"
	"writhed, clasped his\x0d"
	"hands on his chest to\x0d"
	"defend the volume; I\x0d"
	"grasped him with my\x0d"
	"left hand while with\x0d"
	"my right I tried to\x0d"
	"hold the lamp high,\x0d"
	"but I grazed his face\x0d"
	"with the flame, let\x0d"
	"out a muffled cry, al-\x0d"
	"most a roar, as bits\x0d"
	"of paper spilled from\x0d"
	"his mouth, and his\x0d"
	"right hand let go of\x0d"
	"the volume, darted to-\x0d"
	"ward the lamp, and\x0d"
	"abruptly tore it from\x0d"
	"me, flinging it away....\x0d\x0d"
	" The oil spilled out,\x0d"
	"the fire immediately\x0d"
	"seized a fragile\x0d"
	"parchment, which blaz-\x0d"
	"ed up like a bundle\x0d"
	"of dry twigs. Every-\x0d"
	"thing happened in a\x0d"
	"few moments, as if\x0d"
	"for centuries those\x0d"
	"ancient pages had been\x0d"
	"yearning for arson and\x0d"
	"were rejoicing in the\x0d"
	"sudden satisfaction of\x0d"
	"an immemorial thirst\x0d"
	"for ecpyrosis.\x0d\x0d"
	"The Abbey burned for\x0d"
	"three days and three\x0d"
	"nights, and the last\x0d"
	"efforts were of no\x0d"
	"avail. On the third\x0d"
	"day, when the wounded\x0d"
	"had been treated and\x0d"
	"the corpses found out-\x0d"
	"side had been buried,\x0d"
	"the monks and all the\x0d"
	"others collected their\x0d"
	"belongings and abando-\x0d"
	"ned the still-smoking\x0d"
	"abbey, as a place\x0d"
	"accursed.\x0d\x0d"
	" William and I left\x0d"
	"those parts on two\x0d"
	"horses we found as-\x0d"
	"tray in the wood.\x0d"
	"When came to Munich,\x0d"
	"I had to take leave\x0d"
	"of my good master,\x0d"
	"amid many tears. Af-\x0d"
	"ter giving me much\x0d"
	"good advice about my\x0d"
	"future studies, he\x0d"
	"embraced me with a\x0d"
	"father's tenderness\x0d"
	"and dismissed me. I\x0d"
	"never saw him again.\x0d\x0d"
	" Now, on the threshold\x0d"
	"of the death, the more\x0d"
	"I repeat myself the\x0d"
	"story that has emer-\x0d"
	"ged from it, the less\x0d"
	"I manage to under-\x0d"
	"stand whether in it\x0d"
	"there is a design that\x0d"
	"goes beyond the natu-\x0d"
	"ral sequence of the\x0d"
	"events and the times\x0d"
	"that connect them.\x0d"
	"And it is a hard\x0d"
	"thing for this old\x0d"
	"monk, not to know\x0d"
	"whether the letter he\x0d"
	"has written contains\x0d"
	"some hidden meaning,\x0d"
	"or more than one, or\x0d"
	"many, or none at all.\x0d\x0d"
	" But this inability of\x0d"
	"mine to see is per-\x0d"
	"haps the effect of the\x0d"
	"shadow that the great\x0d"
	"darkness, as it appro-\x0d"
	"aches, is casting on\x0d"
	"the aged world. It is\x0d"
	"cold in the scripto-\x0d"
	"rium, my thumb aches.\x0d"
	"I leave this manus-\x0d"
	"cript, I do not know\x0d"
	"for whom; I no longer\x0d"
	"know what it is\x0d"
	"about.\x0d\x0d\x1a"


	,
		// fin textos 1 inglés
		// textos 2 portugues brasil
	

	(const unsigned char*)
	" Desfigurado pela an-\x0d"
	"gústia, pela ação do\x0d"
	"veneno que já serpen-\x0d"
	"tava abundante por\x0d"
	"suas veias, o outrora\x0d"
	"rosto do ancião se via\x0d"
	"agora repulsivo e gro-\x0d"
	"tesco.  Havíamos con-\x0d"
	"seguido prende-lo com\x0d"
	"calma, mas nos preci-\x0d"
	"pitamos com veemência\x0d"
	"sobre ele. Conseguiu\x0d"
	"safar-se e apertou o\x0d"
	"livro contra seu peito\x0d"
	"para defende-lo.  Eu\x0d"
	"o tinha pegado com a\x0d"
	"mão esquerda, enquanto\x0d"
	"com a direita tratava\x0d"
	"de manter a lamparina\x0d"
	"no alto. Contudo, to-\x0d"
	"quei seu rosto com a\x0d"
	"chama e emitiu um\x0d"
	"som abafado, quase um\x0d"
	"rugido, deixando cair\x0d"
	"pedaços de pergaminho\x0d"
	"pela boca.  Sua mão\x0d"
	"direita soltou o li-\x0d"
	"vro, procurou a lam-\x0d"
	"parina e, de um só\x0d"
	"golpe, arrancou-a da\x0d"
	"minha mão lançando-a\x0d"
	"adiante.\x0d\x0d"
	" O azeite derramou, e\x0d"
	"em seguida, o pergami-\x0d"
	"nho foi tomado pelo\x0d"
	"fogo e ardeu como um\x0d"
	"feixe de folhas secas.\x0d"
	"Tudo aconteceu em\x0d"
	"poucos instantes; uma\x0d"
	"labareda elevou-se dos\x0d"
	"livros, como se aque-\x0d"
	"las páginas milenares\x0d"
	"tivessem levado sécu-\x0d"
	"los esperando para\x0d"
	"queimar e alegra-\x0d"
	"ram-se ao satisfazer\x0d"
	"de imediato uma sede\x0d"
	"imemorial de combus-\x0d"
	"tão.\x0d"
	" A abadia ardeu du-\x0d"
	"rante três dias e três\x0d"
	"noites e de nada va-\x0d"
	"leram os últimos es-\x0d"
	"forços.  Ao terceiro\x0d"
	"dia, curados os feridos,\x0d"
	"enterrados os cadáve-\x0d"
	"res que haviam caído\x0d"
	"para fora dos edifí-\x0d"
	"cios, os monges e o\x0d"
	"resto dos habitantes\x0d"
	"da abadia recolheram\x0d"
	"seus pertences e\x0d"
	"abandonaram a meseta,\x0d"
	"que ainda fumegava,\x0d"
	"como um lugar maldito.\x0d\x0d"
	" Guilherme e eu nos\x0d"
	"afastamos daquelas pa-\x0d"
	"ragens em duas monta-\x0d"
	"rias que encontramos\x0d"
	"pelo bosque. Quando\x0d"
	"chegamos a Munique\x0d"
	"tive que me separar,\x0d"
	"não sem derramar\x0d"
	"muitas lágrimas, de\x0d"
	"meu bom mestre.\x0d"
	"Depois de me dar\x0d"
	"bons conselhos para\x0d"
	"meus futuros estudos,\x0d"
	"me apertou entre seus\x0d"
	"braços com a ternura\x0d"
	"de um pai e me disse\x0d"
	"'adeus'. Jamais voltei\x0d"
	"vê-lo.\x0d\x0d"
	" Agora, já sob o um-\x0d"
	"bral da morte, quanto\x0d"
	"mais releio esta his-\x0d"
	"tória e o que dela re-\x0d"
	"sultou, menos sei se\x0d"
	"ela contém ou não\x0d"
	"alguma trama distinta\x0d"
	"além da mera suce-\x0d"
	"ssão natural dos acon-\x0d"
	"tecimentos e dos mo-\x0d"
	"mentos que se rela-\x0d"
	"cionam entre si. Já é\x0d"
	"duro para este velho\x0d"
	"monge não saber se a\x0d"
	"letra que escreveu\x0d"
	"contém ou não algum\x0d"
	"sentido oculto, nem\x0d"
	"se contém mais de um,\x0d"
	"ou muitos, ou nenhum.\x0d\x0d"
	" Mas ainda que esta\x0d"
	"incapacidade seja pro-\x0d"
	"duto da sombra que a\x0d"
	"grande treva que se\x0d"
	"aproxima projeta so-\x0d"
	"bre este mundo já\x0d"
	"velho. Deixo este tex-\x0d"
	"to não sei para quem,\x0d"
	"este texto, que já não\x0d"
	"sei do que fala...\x0d"
	"Faz frio no scripto-\x0d"
	"rium, me dói o\x0d"
	"polegar...\x0d\x0d\x1a"
	,
		// fin textos 2 portugues brasil
		// textos 3 catalán
	


	(const unsigned char*)
	"Desfigurat per l'an-\x0d"
	"goixa, per l'acuit del\x0d"
	"verí que ja serpente-\x0d"
	"java abundant per les\x0d"
	"seves venes, l'antany\x0d"
	"venerable rostre de\x0d"
	"l'ancià es veia repul-\x0d"
	"siu i grotesc. L'hau-\x0d"
	"ríem pogut atrapar\x0d"
	"amb calma, però ens\x0d"
	"precipitàrem amb ve-\x0d"
	"hemència sobre seu.\x0d"
	"Aconseguí escapolir-se\x0d"
	"i va prémer el llibre\x0d"
	"contra el seu pit per\x0d"
	"defensar-lo. Jo el te-\x0d"
	"nia agafat amb la mà\x0d"
	"esquerra, mentre amb\x0d"
	"la dreta intentava\x0d"
	"mantenir la làmpada\x0d"
	"alçada. Però vaig fre-\x0d"
	"gar el seu rostre amb\x0d"
	"la flama i emeté un\x0d"
	"so ofegat, gairebé un\x0d"
	"rugit, deixant caure\x0d"
	"trossos de foli per la\x0d"
	"boca. La seva mà\x0d"
	"dreta deixà anar el\x0d"
	"llibre, va buscar la\x0d"
	"làmpada i, d'un cop,\x0d"
	"me la va arrencar\x0d"
	"llençant-la cap enda-\x0d"
	"vant...\x0d\x0d"
	"S'abocà l'oli i de se-\x0d"
	"guida el foc encengué\x0d"
	"el pergamí que va\x0d"
	"cremar com un feix\x0d"
	"de llenya resseca.\x0d"
	"Tot succeí en pocs\x0d"
	"instants; una flamara-\x0d"
	"da es va elevar des\x0d"
	"dels llibres, com\x0d"
	"si aquelles pàgines\x0d"
	"mil.lenaries portessin\x0d"
	"segles esperant cre-\x0d"
	"mar-se i gaudissin al\x0d"
	"satisfer de sobte una\x0d"
	"set immemorial d'ecpi-\x0d"
	"rosi.\x0d"
	" L'abadia cremà du-\x0d"
	"rant tres dies i tres\x0d"
	"nits i de res valgue-\x0d"
	"ren els seus últims\x0d"
	"esforços. Al tercer\x0d"
	"dia, guarits els ferits,\x0d"
	"enterrats els cadàvers\x0d"
	"que havien quedat fora\x0d"
	"dels edificis, els mon-\x0d"
	"jos i la resta del po-\x0d"
	"bladors de l'abadia re-\x0d"
	"colliren les seves\x0d"
	"pertinences i abando-\x0d"
	"naren l'altiplà, que\x0d"
	"encara fumejava, com\x0d"
	"un lloc maleït.\x0d\x0d"
	" Guillem i jo\x0d"
	"ens vam allunyar\x0d"
	"d'aquell paratge en\x0d"
	"dues cavalcadures que\x0d"
	"trobàrem pel bosc.\x0d"
	"Quan vam arribar a\x0d"
	"Munich vaig haver de\x0d"
	"separar-me, no sense\x0d"
	"vessar abundants llà-\x0d"
	"grimes, del meu bon\x0d"
	"mestre. Després de\x0d"
	"donar-me molts bons\x0d"
	"consells pels meus\x0d"
	"futurs estudis, em va\x0d"
	"estrènyer als seus\x0d"
	"braços, amb la ten-\x0d"
	"dresa d'un pare, i em\x0d"
	"va dir adeu. Ja mai\x0d"
	"vaig tornar a veure'l.\x0d"
	"Ara, ja al llindar de\x0d"
	"la mort, quan més re-\x0d"
	"llegeixo la història que\x0d"
	"en va resultar, menys\x0d"
	"sé si aquesta conté o\x0d"
	"no una trama distin-\x0d"
	"gible de la mera su-\x0d"
	"ccessió natural dels\x0d"
	"esdeveniments i del\x0d"
	"moments que els rela-\x0d"
	"cionen entre si. I és\x0d"
	"dur per aquest vell\x0d"
	"monjo no saber si la\x0d"
	"lletra que ha escrit\x0d"
	"conté o no algun sen-\x0d"
	"tit ocult, ni si en\x0d"
	"conté més d'un, o\x0d"
	"molts, o cap.\x0d\x0d"
	" Però potser aquesta\x0d"
	"incapacitat sigui pro-\x0d"
	"ducte de l'ombra que\x0d"
	"la gran tenebra que\x0d"
	"s'aproxima, projecta\x0d"
	"sobre aquest món ja\x0d"
	"vell. Fa fred al\x0d"
	"scriptorium, em fa\x0d"
	"mal el polze. Deixo\x0d"
	"aquest text, no sé per\x0d"
	"a qui, aquest text,\x0d"
	"que ja no sé de què\x0d"
	"parla.\x0d\x1a"

	,
		// fin textos 3 catalán
		// textos 4 gallego
	

	(const unsigned char*)
	"  Desfigurado pola\x0d"
	"congoxa, polo acoso do\x0d"
	"veleno que xa serpea\x0d"
	"abondo polas súas ve-\x0d"
	"as, a noutrora venera-\x0d"
	"ble face do ancián\x0d"
	"víase noxenta e gro-\x0d"
	"tesca. Poderíamolo ter\x0d"
	"atrapado con calma,\x0d"
	"pero precipitámonos\x0d"
	"con tento sobre el.\x0d"
	"Acadou escapulirse e\x0d"
	"amarrou o libro contra\x0d"
	"o seu peito pra pro-\x0d"
	"texelo. Eu tíñao colli-\x0d"
	"do ca man esquerda,\x0d"
	"namentres coa dereita\x0d"
	"tentaba de manter no\x0d"
	"alto a lámpada. Máis\x0d"
	"rocei a súa face coa\x0d"
	"chama e emanou un\x0d"
	"son afogado, case un\x0d"
	"bramido, deixando caer\x0d"
	"anacos de folio pola\x0d"
	"boca. A súa man de-\x0d"
	"reita soltou o libro,\x0d"
	"procurou a lámpada e,\x0d"
	"dun golpe, arrancouma\x0d"
	"guindándoa cara adian-\x0d"
	"te...\x0d"
	" Derramouse o aceite,\x0d"
	"e axiña prendeu lume\x0d"
	"no pergamiño que ar-\x0d"
	"deu coma un feixe de\x0d"
	"palla reseca. Todo a-\x0d"
	"conteceu nun intre;\x0d"
	"unha labarada ergueu-\x0d"
	"se dende os libros,\x0d"
	"como se aquelas páxi-\x0d"
	"nas milenarias levaran\x0d"
	"séculos agardando quei-\x0d"
	"marse e gozaran ó sa-\x0d"
	"tisfaceres de súpeto\x0d"
	"unha sede inmemorial\x0d"
	"de ecpirosis.\x0d\x0d"
	"  A abadía queimouse\x0d"
	"durante tres días e\x0d"
	"tres noites e de nada\x0d"
	"serviron os derradei-\x0d"
	"ros esforzos. Ao ter-\x0d"
	"ceiro día; sandados os\x0d"
	"feridos, soterrado-los\x0d"
	"mortos que quedaran\x0d"
	"fora dos edificios, os\x0d"
	"monxes e o resto dos\x0d"
	"poboadores da abadía\x0d"
	"recolleron as súas\x0d"
	"pertenzas e abandona-\x0d"
	"ron a meseta, que in-\x0d"
	"da fumeaba, coma un\x0d"
	"lugar maldito.\x0d\x0d"
	"  Guillerme máis eu\x0d"
	"afastámonos daquela\x0d"
	"paraxe en dúas montu-\x0d"
	"ras que atopamos pola\x0d"
	"fraga. Cando chegamos\x0d"
	"a Munich tiven que\x0d"
	"separarme, no sen\x0d"
	"antes verter bagoas\x0d"
	"abondo do meu bo\x0d"
	"mestre. Despois de\x0d"
	"darme moitos bos con-\x0d"
	"sellos pra os meus\x0d"
	"futuros estudos, deume\x0d"
	"unha forte aperta, coa\x0d"
	"tenrura dun pai, e\x0d"
	"dixome adeus. Xamais\x0d"
	"o volvin ver.\x0d\x0d"
	" Agora, preto da miña\x0d"
	"morte, canto máis re-\x0d"
	"leo a historia que delo\x0d"
	"resultou, menos sei se\x0d"
	"esta conten ou non\x0d"
	"unha urda discernible\x0d"
	"da mera sucesión na-\x0d"
	"tural dos feitos e dos\x0d"
	"intres que os relacio-\x0d"
	"nan entre si. Non é\x0d"
	"doado pra este vello\x0d"
	"monxe non saberes se\x0d"
	"a letra que escribiu\x0d"
	"contén ou non algún\x0d"
	"sentido oculto, nin se\x0d"
	"contén máis dun, ou\x0d"
	"moitos, ou ningún.\x0d\x0d"
	" Pero poida que esta\x0d"
	"incapacidade sexa por\x0d"
	"mor da sombra da\x0d"
	"grande tebra que se\x0d"
	"aproxima, proxecta\x0d"
	"sobre este mundo xa\x0d"
	"vello. Vai frio no\x0d"
	"scriptorium, dóeme o\x0d"
	"polgar. Deixo este\x0d"
	"texto, non sei pra\x0d"
	"quen, este texto, que\x0d"
	"xa non sei de que\x0d"
	"fala.\x0d\x1a"

	,
		// fin textos 4 gallego
		// textos 5 italiano
	


	(const unsigned char*)
	"  Sfigurata dall'ansia,\x0d"
	"dall'incombere del ve-\x0d"
	"leno che ormai già gli\x0d"
	"serpeggiava abbondan-\x0d"
	"temente nelle vene,\x0d"
	"quella che era stata\x0d"
	"la figura venerabile\x0d"
	"del vegliardo appariva\x0d"
	"ora disgustosa e grot-\x0d"
	"tesca. Avremmo potuto\x0d"
	"afferrarlo con calma,\x0d"
	"gli precipitammo inve-\x0d"
	"ce addosso con enfasi,\x0d"
	"egli si divincolò, serrò\x0d"
	"le mani sul petto di-\x0d"
	"fendendo il volume, io\x0d"
	"lo tenevo con la si-\x0d"
	"nistra mentre con la\x0d"
	"destra cercavo di te-\x0d"
	"nere alto il lume, ma\x0d"
	"gli sfiorai il volto con\x0d"
	"la fiamma, egli avver-\x0d"
	"tì il calore, emise un\x0d"
	"suono soffocato, un\x0d"
	"ruggito, quasi, lascian-\x0d"
	"do cadere dalla bocca\x0d"
	"pezzi di carta, abban-\x0d"
	"donò con la destra la\x0d"
	"presa sul libro, mosse\x0d"
	"la mano verso il lume\x0d"
	"e me lo strappò di\x0d"
	"colpo, lanciandolo in\x0d"
	"avanti...\x0d\x0d"
	"  L'olio si versò, il\x0d"
	"fuoco si apprese su-\x0d"
	"bito a una pergamena\x0d"
	"fragilissima che di-\x0d"
	"vampò come un fascio di\x0d"
	"sterpi secchi. Tutto\x0d"
	"avvenne in pochi atti-\x0d"
	"mi, una vampata si\x0d"
	"levò dai volumi, come\x0d"
	"se quelle pagine mille-\x0d"
	"narie anelassero da\x0d"
	"secoli all'arsione e\x0d"
	"gioissero nel soddis-\x0d"
	"fare di colpo una im-\x0d"
	"memoriale sete di\x0d"
	"ecpirosi.\x0d"

	"  L'abbazia arse per\x0d"
	"tre giorni e per tre\x0d"
	"notti e a nulla val-\x0d"
	"sero gli ultimi sforzi.\x0d"
	"Al terzo giorno, curati\x0d"
	"i feriti, seppelliti i\x0d"
	"cadaveri rimasti allo\x0d"
	"scoperto, i monaci e\x0d"
	"tutti gli altri raccol-\x0d"
	"sero le loro cose e\x0d"
	"abbandonarono il pia-\x0d"
	"noro ancora fumante,\x0d"
	"come un luogo male-\x0d"
	"detto.\x0d\x0d"
	"  Guglielmo e io las-\x0d"
	"ciammo quei luoghi, su\x0d"
	"due cavalcature trova-\x0d"
	"te smarrite nel bosco.\x0d\x0d"
	"  Come giungemmo a\x0d"
	"Monaco di Baviera io\x0d"
	"dovetti separarmi, tra\x0d"
	"molte lacrime, dal mio\x0d"
	"buon maestro. Il ma-\x0d"
	"estro mi diede molti\x0d"
	"buoni consigli per i\x0d"
	"miei studi futuri. Poi\x0d"
	"mi abbracciò forte,\x0d"
	"con la tenerezza di un\x0d"
	"padre, e mi congedò.\x0d"
	"Non lo vidi più.\x0d\x0d"
	"  Più recito a me\x0d"
	"stesso la storia che\x0d"
	"ne è sortita, meno\x0d"
	"riesco a capire se in\x0d"
	"essa vi sia una trama\x0d"
	"che vada al di là della\x0d"
	"sequenza naturale degli\x0d"
	"eventi e dei tempi che\x0d"
	"li connettono. Ed è\x0d"
	"cosa dura per questo\x0d"
	"vecchio monaco, alle\x0d"
	"soglie della morte, non\x0d"
	"sapere se la lettera\x0d"
	"che ha scritto contenga\x0d"
	"un qualche senso nas-\x0d"
	"costo, e se più d'uno,\x0d"
	"e molti, o nessuno.\x0d"

	"  Ma questa mia ina-\x0d"
	"bilità a vedere è for-\x0d"
	"se effetto dell'ombra\x0d"
	"che la grande tenebra\x0d"
	"che si avvicina sta\x0d"
	"gettando sul mondo in-\x0d"
	"canutito.\x0d\x0d"
	"  Fa freddo nello\x0d"
	"scriptorium, il pollice\x0d"
	"mi duole. Lascio ques-\x0d"
	"ta scrittura non so\x0d"
	"per chi, non so più\x0d"
	"intorno a che cosa.\x0d\x1a"


	,
		// fin textos 5 italiano
		// textos 6 fines
	

	(const unsigned char*)
	" Olennon suonissa\x0d"
	"runsaana jo kiertävä\x0d"
	"myrkky oli muuttanut\x0d"
	"iljettäväksi ja gro-\x0d"
	"teskiksi sen hahmon,\x0d"
	"joka ennen oli näyt-\x0d"
	"tänyt kunnianarvoi-\x0d"
	"salta vanhukselta.\x0d"
	"Olisimme voineet tart-\x0d"
	"tua käneen rauhalli-\x0d"
	"sesti, mutta hyökkä-\x0d"
	"simme kiivaasti häneen\x0d"
	"kimppuunsa. Hän kie-\x0d"
	"murteli käsissämme ja\x0d"
	"puristi kädet rinta-\x0d"
	"ansa vasten suojellak-\x0d"
	"seen kirjaa. Minä\x0d"
	"pitelin häntä vasem-\x0d"
	"malla kädelläni, kun\x0d"
	"taas oikealla yritin\x0d"
	"pitää lamppua korkea-\x0d"
	"lla, mutta liekki hi-\x0d"
	"paisi hänen kasvojaan\x0d"
	"ja kuumuuden tunties-\x0d"
	"saan häneltä pääsi\x0d"
	"tukahtunut ääni, mel-\x0d"
	"kein karjaisu, ja\x0d"
	"pergamentin palasten\x0d"
	"putoillessa hänen suus-\x0d"
	"taan hän hellitti\x0d"
	"otteensa kirjasta,\x0d"
	"ojensi kätensä lamp-\x0d"
	"pua kohti ja sieppasi\x0d"
	"sen äkkiä kädestäni\x0d"
	"heittäen sen sitten\x0d"
	"eteenpäin...\x0d\x0d"
	" Öljy valui ulos lam-\x0d"
	"pusta ja tuli tarttui\x0d"
	"heti hauraaseen per-\x0d"
	"gamenttiin, joka lei-\x0d"
	"mahti liekkiin kuin\x0d"
	"kuivat risut. Kaikki\x0d"
	"tapahtui muutamassa\x0d"
	"hetkessä, teoksista\x0d"
	"leimahti semmoinen li-\x0d"
	"eska, että olisi saat-\x0d"
	"tanut noiden tuhannen\x0d"
	"vuoden ikäisten kirjo-\x0d"
	"jen jo vuosisatoja\x0d"
	"palaneen halusta pääs-\x0d"
	"tä poltettaviksi ja\x0d"
	"riemuitsevan nyt tyy-\x0d"
	"dyttäessään tämän iki-\x0d"
	"muistoisista ajoista\x0d"
	"vallinneen ekpyrosik-\x0d"
	"sen janonsa.\x0d\x0d"
	"Luostari paloi kolme\x0d"
	"päivää ja yötä, eikä\x0d"
	"viimeisistä ponnistuk-\x0d"
	"sista sen pelastami-\x0d"
	"seksi ollut mitään\x0d"
	"hyötyä. Kolmantena\x0d"
	"päivänä, kun haavoit-\x0d"
	"tuneet oli hoidettu ja\x0d"
	"näkyviin jääneet kuol-\x0d"
	"leet haudattu, kokosi-\x0d"
	"vat munkit ja muu\x0d"
	"väki tavaransa ja läh-\x0d"
	"tivät vielä savuavalta\x0d"
	"tasanteelta, ikään kuin\x0d"
	"jättäisivät paikan jo-\x0d"
	"ka oli kirottu.\x0d\x0d"
	"William ja minä läh-\x0d"
	"dimme tuosta paikasta\x0d"
	"kahdella ratsulla, jotka\x0d"
	"löysimme metsästä\x0d"
	"harhailemasta. Baije-\x0d"
	"rin Müncheniin saa-\x0d"
	"vuttuamme oli minun\x0d"
	"monia kyyneleitä vuo-\x0d"
	"dattaen erottava hy-\x0d"
	"västä mestaristani.\x0d"
	"Mestarini antoi minu-\x0d"
	"lle paljon hyviä neu-\x0d"
	"voja vastaisten opin-\x0d"
	"tojeni varalle. Sitten\x0d"
	"hän syleili minua lu-\x0d"
	"jasti ja hellästi kuin\x0d"
	"isä ja jätti minulle\x0d"
	"hyvästit. En nähnyt\x0d"
	"häntä enää.\x0d\x0d"
	"Seisoessani jo kuole-\x0d"
	"man kynnyksellä ja\x0d"
	"kerratessani tätä ta-\x0d"
	"rinaa, sitä vähemmän\x0d"
	"käsitän onko siinä jo-\x0d"
	"kin juoni, joka si-\x0d"
	"sältää enemmän kuin\x0d"
	"tapahtumasarjojen ku-\x0d"
	"lun ja sen aikakauden,\x0d"
	"johon ne liittyvät.\x0d"
	"Ja on kovaa tälle\x0d"
	"vanhalle munkille, että\x0d"
	"hän ei tiedä sisältääkö\x0d"
	"tämä hänen kirjoituk-\x0d"
	"sensa jonkin kätketyn\x0d"
	"tarkoituksen - ja\x0d"
	"useammanko kuin yh-\x0d"
	"den, moniako vai eikö\x0d"
	"yhtään.\x0d\x0d"
	"Mutta tämä kykene-\x0d"
	"mättömyyteni nähdä\x0d"
	"johtuu ehkä siitä suu-\x0d"
	"resta varjosta, jonka\x0d"
	"lähestyvä suuri pimeys\x0d"
	"langettaa vanhentunee-\x0d"
	"seen maailmaan.\x0d\x0d"
	" Kirjoitussalissa on\x0d"
	"kylmä, peukaloani sär-\x0d"
	"kee. Jätän tämän kir-\x0d"
	"joituksen, en tiedä\x0d"
	"kenelle, enkä enää\x0d"
	"tiedä mistä se kertoo:\x0d"
	"stat rosa pristina\x0d"
	"nomine, nomina nuda\x0d"
	"tenemus.\x0d\x1a"


	,
		// fin textos 6 fines
		// textos 7 portugues
	

	(const unsigned char*)
	" Desfigurado pela an-\x0d"
	"siedade, pelo ataque do\x0d"
	"veneno que agora já\x0d"
	"lhe serpenteava abun-\x0d"
	"dantemente nas veias,\x0d"
	"pela sua desesperada\x0d"
	"e diabólica determina-\x0d"
	"ção, aquela que tinha\x0d"
	"sido a figura venerá-\x0d"
	"vel do velho parecia\x0d"
	"agora repugnante e\x0d"
	"grotesca. Poderíamos\x0d"
	"tê-lo agarrado com\x0d"
	"calma, em vez disso\x0d"
	"precipitámo-nos sobre\x0d"
	"ele com ênfase, ele\x0d"
	"debateu-se, apertou as\x0d"
	"mãos sobre o peito\x0d"
	"defendendo o volume,\x0d"
	"eu segurava-o com a\x0d"
	"mão esquerda enquanto\x0d"
	"com a direita procu-\x0d"
	"rava manter alta a\x0d"
	"candeia, mas rocei-lhe\x0d"
	"o rosto com a chama,\x0d"
	"ele presentiu o calor,\x0d"
	"emitiu um som sufoca-\x0d"
	"do, um rugido, quase,\x0d"
	"deixando cair da boca\x0d"
	"pedaços de papel,\x0d"
	"abandonou a mão direi-\x0d"
	"ta com que agarrava\x0d"
	"o livro, moveu a mão\x0d"
	"para a candeia e\x0d"
	"arrebatou-ma de re-\x0d"
	"pente, lançando-a para\x0d"
	"a frente...\x0d\x0d"
	" O azeite entornou-se,\x0d"
	"o fogo pegou-se logo\x0d"
	"a um pergaminho fra-\x0d"
	"gilíssimo que ardeu\x0d"
	"como um feixe de\x0d"
	"galhos secos. Tudo\x0d"
	"aconteceu em poucos\x0d"
	"instantes, uma grande\x0d"
	"labareda elevou-se dos\x0d"
	"volumes, como se a-\x0d"
	"quelas páginas milená-\x0d"
	"rias anelassem há\x0d"
	"séculos pelo ardor e\x0d"
	"se alegrassem em sa-\x0d"
	"tisfazer de repente\x0d"
	"uma imemorial sede\x0d"
	"de ecpirose.\x0d\x0d"
	" A abadia ardeu du-\x0d"
	"rante três dias e du-\x0d"
	"rante três noites, e\x0d"
	"de nada valeram os\x0d"
	"últimos esforços. No\x0d"
	"terceiro dia, tratados\x0d"
	"os feridos, sepultados\x0d"
	"os cadáveres que fi-\x0d"
	"caram a descoberto,\x0d"
	"os monges e todos os\x0d"
	"outros recolheram as\x0d"
	"suas coisas e abando-\x0d"
	"naram o planalto fu-\x0d"
	"megante, como um lu-\x0d"
	"gar maldito.\x0d\x0d"
	" Guilherme e eu dei-\x0d"
	"xámos aqueles lugares\x0d"
	"em duas cavalgaduras\x0d"
	"encontradas perdidas\x0d"
	"no bosque. Logo que\x0d"
	"chegámos a Munique\x0d"
	"tive de me separar,\x0d"
	"no meio de muitas lá-\x0d"
	"grimas, do meu bom\x0d"
	"mestre. Deu-me mui-\x0d"
	"tos e bons conselhos\x0d"
	"para os meus estudos\x0d"
	"futuros, abraçou-me\x0d"
	"fortemente, com a\x0d"
	"ternura de um pai, e\x0d"
	"disse-me adeus. Não\x0d"
	"o vi mais. Agora, às\x0d"
	"portas da morte, quan-\x0d"
	"to mais recito a mim\x0d"
	"mesmo a história que\x0d"
	"daí saiu menos consi-\x0d"
	"go compreender se\x0d"
	"nela há uma trama\x0d"
	"que vai para além da\x0d"
	"sequência natural dos\x0d"
	"eventos e dos tempos\x0d"
	"que os relacionam en-\x0d"
	"tre si. E é coisa du-\x0d"
	"ra para este velho\x0d"
	"monge, não saber se\x0d"
	"a letra que escreveu\x0d"
	"contém algum sentido\x0d"
	"oculto, e se contém\x0d"
	"mais de um, muitos,\x0d"
	"ou nenhum. Mas esta\x0d"
	"minha inabilidade para\x0d"
	"ver é talvez efeito\x0d"
	"da sombra que a gran-\x0d"
	"de treva que se avi-\x0d"
	"zinha projecta sobre\x0d"
	"o mundo já velho.\x0d"
	"Está frio no scrip-\x0d"
	"torium, dói-me o po-\x0d"
	"legar. Deixo esta es-\x0d"
	"critura, não sei para\x0d"
	"quem, já não sei a\x0d"
	"a propósito de quê.\x0d\x1a"


	,
		// fin textos 7 portugues
	};

/////////////////////////////////////////////////////////////////////////////
// pergamino con las referencias mostradas en la ayuda
/////////////////////////////////////////////////////////////////////////////
// 666 777 TODO falta añadir las referencias de las versiones DC y MAC
const unsigned char * Pergamino::pergaminoReferencias[8] = 
	{
		// texto 0 castellano
	(const unsigned char*)
	"REFERENCIAS\x0d"
	"Traducción inglés:\x0d"
	"    Antonio Giner\x0d"
	"Traducción brasileño:\x0d"
	"    Antonio Pimentel\x0d"
	"Traducción catalán:\x0d"
	"    Efren Garcia\x0d"
	"Traducción gallego:\x0d"
	"    Marcos Maceda\x0d\x0a"
	"Traducción italiano:\x0d"
	"    Chiara Bagnoli\x0d"
	"Traducción finés:\x0d"
	"    Riikka Halonen\x0d"
	"Traducción portugués:\x0d"
	"    Filipe Silva\x0d\x0a"
	"Código original:\x0d"
	"    Paco Menéndez\x0d"
	"Gráficos y carátula\x0d"
	"    Juán Delcán\x0d"
	"Reingeniería inversa:\x0d"
	"    Manuel Abadía\x0d"
	"Versión SDL: Luzbel\x0d"
	"Gráficos VGA:\x0d"
	"    Antonio Giner\x0d\x1a"
		// fin textos 0 castellano
	,
		// textos 1 inglés
	

	(const unsigned char*)
	"Not translated yet"
	"\x1a"


	,
		// fin textos 1 inglés
		// textos 2 portugues brasil
	

	(const unsigned char*)
	"Not translated yet\x1a"
	,
		// fin textos 2 portugues brasil
		// textos 3 catalán
	(const unsigned char*)
	"No traducido aún"
	"\x1a"
	,
		// fin textos 3 catalán
		// textos 4 gallego
	(const unsigned char*)
	"No traducido aún"
	"\x1a"
	,
		// fin textos 4 gallego
		// textos 5 italiano
	(const unsigned char*)
	"Not translated yet"
	"\x1a"
	,
		// fin textos 5 italiano
		// textos 6 fines
	

	(const unsigned char*)
	"Not translated yet"
	"\x1a"
	,
		// fin textos 6 fines
		// textos 7 portugues
	

	(const unsigned char*)
	"Not translated yet"
	"\x1a"
	,
		// fin textos 7 portugues
	};

/*
/////////////////////////////////////////////////////////////////////////////
// pergamino con las referencias mostradas en la ayuda
/////////////////////////////////////////////////////////////////////////////

const unsigned char * Pergamino::pergaminoAyudasyMejoras[8] = 
	{
// NO ESTA DEFINIDO EL caracter 5 para los pergaminos
// no podemos poner F5
		// texto 0 castellano
	(const unsigned char*)
	"Ayudas y mejoras\x0d\x0d"
	"G: Grabar la partida\x0d"
	"C: Cargar la partida\x0d"
	"F2: Cambiar entre \x0d"
	"gráficos VGA-CPC\x0d"
	"F3: Pantalla completa\x0d"
	"F5: Mostrar mapas\x0d"
	"1: Dejad pulsada para\x0d"
	"seguir al abad\x0d"
	"Traducción gallego:\x0d"
	"    Marcos Maceda\x0d\x0a"
	"Traducción italiano:\x0d"
	"    Chiara Bagnoli\x0d"
	"Traducción finés:\x0d"
	"    Riikka Halonen\x0d"
	"Traducción portugués:\x0d"
	"    Filipe Silva\x0d\x0a"
	"Código original:\x0d"
	"    Paco Menéndez\x0d"
	"Gráficos y carátula\x0d"
	"    Juán Delcán\x0d"
	"Reingeniería inversa:\x0d"
	"    Manuel Abadía\x0d"
	"Versión SDL: Luzbel\x0d"
	"Gráficos VGA:\x0d"
	"    Antonio Giner\x0d\x1a"
		// fin textos 0 castellano
	,
		// textos 1 inglés
	

	(const unsigned char*)
	" "
	"\x1a"


	,
		// fin textos 1 inglés
		// textos 2 portugues brasil
	

	(const unsigned char*)
	"\x1a"
	,
		// fin textos 2 portugues brasil
		// textos 3 catalán
	(const unsigned char*)
	"\x1a"
	,
		// fin textos 3 catalán
		// textos 4 gallego
	(const unsigned char*)
	"\x1a"
	,
		// fin textos 4 gallego
		// textos 5 italiano
	(const unsigned char*)
	"\x1a"
	,
		// fin textos 5 italiano
		// textos 6 fines
	

	(const unsigned char*)
	"\x1a"
	,
		// fin textos 6 fines
		// textos 7 portugues
	

	(const unsigned char*)
	"\x1a"
	,
		// fin textos 7 portugues
	};

*/


/////////////////////////////////////////////////////////////////////////////
// pergamino con la ayuda del manejo del teclado
/////////////////////////////////////////////////////////////////////////////

const unsigned char * Pergamino::pergaminoManejo[8] = 
	{
		// texto 0 castellano
	(const unsigned char*)
	"  MANEJO DEL\x0d"
	"   TECLADO\x0d\x0d"  
	"Su novicio puede ser\x0d"
	"manejado, aunque todo\x0d"
	"dentro de la pantalla\x0d"
	"en la que se encuen-\x0d"
	"tra Guillermo, con la\x0d" 
	"tecla cursor abajo.\x0d"
	"Mientras se pulse esta\x0d"
	" tecla, el novicio se \x0d"
	"dirigirá a la misma \x0d"
	"dirección a la que \x0d"
	"mire Guillermo, a me-\x0d"
	"nos que se encuentre \x0d" 
	"un obstáculo.\x0d\x0d\x0d\x0a"
	"Para coger objetos, \x0d"
	"basta con colocarse \x0d"
	"enfrente de éstos. \x0d"
	"Guillermo puede coger \x0d"
	"seis objetos y su \x0d"
	"novicio otros dos dis-\x0d"
	"tintos. Para dejar los\x0d"
	"objetos se puede pul-\x0d"
	"sar Espacio, dejándose \x0d"
	"siempre el objeto que \x0d"
	"aparece más a la iz-\x0d"
	"quierda del marcador, \x0d"
	"en el que sólo apare-\x0d"
	"cen los objetos que \x0d"
	"lleva Guillermo y son \x0d"
	"los únicos que se \x0d"
	"pueden dejar.\x1a"
		// fin textos 0 castellano
	,
		// textos 1 inglés
	

	(const unsigned char*)
	"Not translated yet"
	"\x1a"


	,
		// fin textos 1 inglés
		// textos 2 portugues brasil
	

	(const unsigned char*)
	"Not translated yet"
	"\x1a"
	,
		// fin textos 2 portugues brasil
		// textos 3 catalán
	(const unsigned char*)
	"No traducido aún"
	"\x1a"
	,
		// fin textos 3 catalán
		// textos 4 gallego
	(const unsigned char*)
	"No traducido aún"
	"\x1a"
	,
		// fin textos 4 gallego
		// textos 5 italiano
	(const unsigned char*)
	"Not translated yet"
	"\x1a"
	,
		// fin textos 5 italiano
		// textos 6 fines
	

	(const unsigned char*)
	"Not translated yet"
	"\x1a"
	,
		// fin textos 6 fines
		// textos 7 portugues
	

	(const unsigned char*)
	"Not translated yet"
	"\x1a"
	,
		// fin textos 7 portugues
	};

/////////////////////////////////////////////////////////////////////////////
// pergamino con el texto de introduccion para la ayuda
/////////////////////////////////////////////////////////////////////////////

const unsigned char * Pergamino::pergaminoIntroduccion[8] = 
	{
		// texto 0 castellano
	(const unsigned char*)
	"'No sigáis varias y \x0d"
	"extrañas doctrinas so-\x0d"
	"físticas que esparcen \x0d"
	"pestífera semilla' es-\x0d"
	"cribía el mismísimo \x0d"
	"Clemente VI en el \x0d"
	"año mil trescientos \x0d"
	"cuarenta y seis a los\x0d"
	"maestros y alumnos de\x0d"
	"la Universidad de Pa-\x0d"
	"rís. El Pontífice se \x0d"
	"refería en aquella \x0d"
	"carta a las doctrinas\x0d"
	"de un ilustre monje \x0d"
	"franciscano de origen\x0d"
	"inglés, llamado Gui-\x0d"
	"llermo de Occam, \x0d"
	"huido varios años an-\x0d"
	"tes de las cárceles \x0d"
	"de Avignon acusado de\x0d"
	"herejía. Durante cua-\x0d"
	"tro años había estado\x0d"
	"retenido, hasta que \x0d"
	"logró fugarse y pedir\x0d"
	"asilo en la corte del\x0d"
	"Emperador Luis de \x0d"
	"Baviera, por entonces \x0d"
	"enemistado con el Pa-\x0d"
	"pa Juan XXII. Muer-\x0d"
	"to el Emperador, Gui-\x0d"
	"llermo quiso volver a\x0d"
	"la misión con su or-\x0d"
	"den y con la Iglesia,\x0d" 
	"motivo por el que \x0d"
	"viajó a Italia acom-\x0d"
	"pañado de su joven \x0d"
	"novicio para entre-\x0d"
	"vistarse con Bernardo\x0d"
	"Güi, entonces máximo \x0d"
	"responsable de la In-\x0d"
	"quisición en aquella \x0d"
	"zona y representante,\x0d"
	"en definitiva, del Pon-\x0d"
	"tífice.\x0d\x0d\x0a"
	"No consta, sin embar-\x0d"
	"go, con certeza, si en\x0d"
	"realidad Guillermo \x0d"
	"consiguió su objeti-\x0d"
	"vo. Tan sólo el testi-\x0d"
	"monio dejado por su \x0d"
	"discípulo muchos años\x0d"
	"más tarde en una co-\x0d"
	"lección de pergaminos\x0d"	
	", donde se relatan los\x0d"
	"hechos asombrosos y \x0d"
	"terribles que aconte-\x0d"
	"cieron durante la se-\x0d"
	"mana que permanecie-\x0d"
	"ron en la Abadía en \x0d"
	"la que debería cele-\x0d"
	"brarse aquella entre-\x0d"
	"vista.\x0d\x0d\x0a"
	"El testimonio de la \x0d"
	"historia que ahora \x0d"
	"vas a revivir...\x0d\x1a"
		// fin textos 0 castellano
	,
		// textos 1 inglés
	

	(const unsigned char*)
	"Not translated yet"
	"\x1a"


	,
		// fin textos 1 inglés
		// textos 2 portugues brasil
	

	(const unsigned char*)
	"Not translated yet"
	"\x1a"
	,
		// fin textos 2 portugues brasil
		// textos 3 catalán
	(const unsigned char*)
	"No traducido aún"
	"\x1a"
	,
		// fin textos 3 catalán
		// textos 4 gallego
	(const unsigned char*)
	"No traducido aún"
	"\x1a"
	,
		// fin textos 4 gallego
		// textos 5 italiano
	(const unsigned char*)
	"Not translated yet"
	"\x1a"
	,
		// fin textos 5 italiano
		// textos 6 fines
	

	(const unsigned char*)
	"Not translated yet"
	"\x1a"
	,
		// fin textos 6 fines
		// textos 7 portugues
	

	(const unsigned char*)
	"Not translated yet"
	"\x1a"
	,
		// fin textos 7 portugues
	};


